name: UT test
on: [push, pull_request]
jobs:
  run:
    runs-on: windows-latest
    name: Build, Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'
        id: checkout_code
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild
      - name: Run MSBuild
        id: run_msbuild
        run: msbuild /p:Configuration=Debug /p:Platform=x86 HelloCovDemo.sln
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest
      - name: Run UT
        id: run_ut
        shell: cmd
        run: vstest.console.exe Debug\HelloTest.dll
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8  # You can specify the Python version you need
      - name: Send Email
        id: send_email
        shell: cmd
        run: python sendEmail.py "${{github.event.head_commit.committer.username }}" "hui.zhang@broadcom.com" "${{ github.repository }}/commit/${{ github.sha }}.patch"

